# Generated by Django 6.0.4 on 2026-04-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=50)),
                ('platforms', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='games/covers/')),
            ],
            options={
                'verbose_name_plural': 'Games',
                'ordering': ('name',),
            },
        ),
    ]
